<h1> Loading Training Sets </h1>

In [4]:
import pickle

pickle_in = open("Training_Sets/N_X10weekly.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("Training_Sets/N_Y10weekly.pickle","rb")
Y = pickle.load(pickle_in)

<h1> Train/Test Split </h1>

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.10)

X_train = np.asarray(X_train)
X_test = np.asarray(X_test)
Y_train = np.asarray(Y_train)
Y_test = np.asarray(Y_test)

print (Y_train)

[[0]
 [1]
 [0]
 ...
 [1]
 [1]
 [0]]


In [6]:
from keras import backend as K

def sensitivity(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    recall = true_positives / (possible_positives + K.epsilon())
    return recall

C:\Users\Bikal\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


<h1> Artificial Neural Network 

In [7]:
import tensorflow as tf
from keras.regularizers import l2
from keras import losses
model = tf.keras.models.Sequential()
from keras import regularizers

model.add(tf.keras.layers.Flatten(input_shape=X_train[0].shape))

model.add(tf.keras.layers.Dense(20, kernel_regularizer= regularizers.l2(0.55), activation = tf.nn.relu))
model.add(tf.keras.layers.BatchNormalization())

model.add(tf.keras.layers.Dense(10, kernel_regularizer= regularizers.l2(0.6),   activation = tf.nn.relu))
model.add(tf.keras.layers.BatchNormalization())

#  
#  kernel_regularizer = regularizers.l2(0.001) ,

# model.add(tf.keras.layers.Dense(20, activation = tf.nn.relu))

# model.add(tf.keras.layers.Dense(512, activation = tf.nn.relu))
# model.add(tf.keras.layers.Dense(4, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(2, activation = tf.nn.relu))


model.add(tf.keras.layers.Dense(1, activation = tf.nn.sigmoid))
model.compile(optimizer = tf.keras.optimizers.Adam(lr=0.0001, decay = 0.0001),
loss = losses.binary_crossentropy,
 metrics =[sensitivity, 'accuracy'])

In [8]:
model.fit(X_train, Y_train, epochs=100, validation_data = (X_test, Y_test))

Train on 1386 samples, validate on 154 samples
Epoch 1/100
1386/1386 [==============================] - 1s 596us/step - loss: 19.1927 - sensitivity: 0.5209 - acc: 0.4762 - val_loss: 18.8391 - val_sensitivity: 0.7409 - val_acc: 0.4675
Epoch 2/100
1386/1386 [==============================] - 0s 53us/step - loss: 18.6101 - sensitivity: 0.4687 - acc: 0.4820 - val_loss: 18.2793 - val_sensitivity: 0.9173 - val_acc: 0.5260
Epoch 3/100
1386/1386 [==============================] - 0s 46us/step - loss: 18.0531 - sensitivity: 0.4677 - acc: 0.4978 - val_loss: 17.7370 - val_sensitivity: 0.9074 - val_acc: 0.5195
Epoch 4/100
1386/1386 [==============================] - 0s 46us/step - loss: 17.5119 - sensitivity: 0.4649 - acc: 0.4957 - val_loss: 17.2090 - val_sensitivity: 0.8975 - val_acc: 0.5260
Epoch 5/100
1386/1386 [==============================] - 0s 46us/step - loss: 16.9922 - sensitivity: 0.4661 - acc: 0.4971 - val_loss: 16.6974 - val_sensitivity: 0.7880 - val_acc: 0.4935
Epoch 6/100
1386/1386 

Epoch 45/100
1386/1386 [==============================] - 0s 48us/step - loss: 5.3354 - sensitivity: 0.4123 - acc: 0.5455 - val_loss: 5.2863 - val_sensitivity: 0.2642 - val_acc: 0.4286
Epoch 46/100
1386/1386 [==============================] - 0s 45us/step - loss: 5.1920 - sensitivity: 0.4245 - acc: 0.5570 - val_loss: 5.1407 - val_sensitivity: 0.2642 - val_acc: 0.4416
Epoch 47/100
1386/1386 [==============================] - 0s 49us/step - loss: 5.0433 - sensitivity: 0.4359 - acc: 0.5570 - val_loss: 5.0010 - val_sensitivity: 0.2642 - val_acc: 0.4286
Epoch 48/100
1386/1386 [==============================] - 0s 45us/step - loss: 4.9041 - sensitivity: 0.4172 - acc: 0.5664 - val_loss: 4.8647 - val_sensitivity: 0.2772 - val_acc: 0.4156
Epoch 49/100
1386/1386 [==============================] - 0s 46us/step - loss: 4.7680 - sensitivity: 0.4237 - acc: 0.5628 - val_loss: 4.7303 - val_sensitivity: 0.2772 - val_acc: 0.4221
Epoch 50/100
1386/1386 [==============================] - 0s 47us/step - lo

1386/1386 [==============================] - 0s 46us/step - loss: 1.6800 - sensitivity: 0.4603 - acc: 0.5909 - val_loss: 1.6991 - val_sensitivity: 0.3122 - val_acc: 0.4870
Epoch 90/100
1386/1386 [==============================] - 0s 45us/step - loss: 1.6406 - sensitivity: 0.4534 - acc: 0.5815 - val_loss: 1.6634 - val_sensitivity: 0.2992 - val_acc: 0.4675
Epoch 91/100
1386/1386 [==============================] - 0s 45us/step - loss: 1.6068 - sensitivity: 0.4568 - acc: 0.5945 - val_loss: 1.6278 - val_sensitivity: 0.2992 - val_acc: 0.4870
Epoch 92/100
1386/1386 [==============================] - 0s 46us/step - loss: 1.5660 - sensitivity: 0.4484 - acc: 0.5859 - val_loss: 1.5927 - val_sensitivity: 0.2981 - val_acc: 0.4805
Epoch 93/100
1386/1386 [==============================] - 0s 45us/step - loss: 1.5387 - sensitivity: 0.4551 - acc: 0.5981 - val_loss: 1.5584 - val_sensitivity: 0.2981 - val_acc: 0.4870
Epoch 94/100
1386/1386 [==============================] - 0s 45us/step - loss: 1.4986 - 

In [9]:
model.evaluate(X_test, Y_test)

154/154 [==============================] - 0s 26us/step


[1.3634620301135174, 0.2981137950699051, 0.4740259744130172]

In [10]:
predictions = model.predict(X_test)
print (predictions)

[[0.57086337]
 [0.48277313]
 [0.30948868]
 [0.4751724 ]
 [0.36198717]
 [0.468186  ]
 [0.36117578]
 [0.36647013]
 [0.48277313]
 [0.48277313]
 [0.62239456]
 [0.48277313]
 [0.63872296]
 [0.5645997 ]
 [0.48277313]
 [0.51534545]
 [0.48277313]
 [0.67355365]
 [0.48277313]
 [0.48277313]
 [0.48277313]
 [0.48277313]
 [0.48277313]
 [0.37234777]
 [0.48277313]
 [0.48277313]
 [0.3301122 ]
 [0.4171414 ]
 [0.664682  ]
 [0.48277313]
 [0.5707239 ]
 [0.54603136]
 [0.48277313]
 [0.48277313]
 [0.48277313]
 [0.35335284]
 [0.48277313]
 [0.6576695 ]
 [0.46882442]
 [0.43642724]
 [0.48277313]
 [0.48277313]
 [0.48277313]
 [0.81568533]
 [0.35193586]
 [0.63877815]
 [0.63441026]
 [0.47521988]
 [0.48277313]
 [0.5134417 ]
 [0.48277313]
 [0.5316906 ]
 [0.49744955]
 [0.48277313]
 [0.35558805]
 [0.5563802 ]
 [0.411315  ]
 [0.48277313]
 [0.5508251 ]
 [0.55349153]
 [0.50067747]
 [0.48277313]
 [0.48277313]
 [0.48277313]
 [0.48277313]
 [0.48277313]
 [0.48543364]
 [0.53360766]
 [0.48277313]
 [0.29576275]
 [0.53583443]
 [0.58

<h1> Saving the Model

In [95]:
model.save('WeeklyANNFeb.model')


<h1> <b> K nearest Neigbor </b>

In [11]:
from sklearn.neighbors import KNeighborsClassifier

accuracies = {}

for i in range(1,300):
    knn = KNeighborsClassifier(n_neighbors = i)

    dataset_size = len(X_train)
    TwoDim_dataset = X_train.reshape(dataset_size,-1)
   
    
    
    
    # fitting the model
    knn.fit(TwoDim_dataset, Y_train)


    # predict the response
    dataset_size = len(X_test)
    TwoDim_dataset = X_test.reshape(dataset_size,-1)
    pred = knn.predict(TwoDim_dataset)
    accu = knn.score(TwoDim_dataset, Y_test)
    accuracy = []
    for u,j in zip(pred, Y_test):
        if u == j:
            accuracy.append(1)
        else:
            accuracy.append(0)

    accurate_predictions = [x for x in accuracy if x == 1]
    acc = (len(accurate_predictions) / len(accuracy))

    print(i, acc)

C:\Users\Bikal\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  from ipykernel import kernelapp as app


1 0.551948051948052
2 0.5194805194805194
3 0.5454545454545454
4 0.525974025974026
5 0.538961038961039
6 0.5194805194805194
7 0.512987012987013
8 0.4935064935064935
9 0.538961038961039
10 0.538961038961039
11 0.551948051948052
12 0.5714285714285714
13 0.5714285714285714
14 0.5324675324675324
15 0.551948051948052
16 0.525974025974026
17 0.5324675324675324
18 0.512987012987013
19 0.5194805194805194
20 0.5194805194805194
21 0.5064935064935064
22 0.5
23 0.512987012987013
24 0.525974025974026
25 0.551948051948052
26 0.5324675324675324
27 0.538961038961039
28 0.5324675324675324
29 0.538961038961039
30 0.5454545454545454
31 0.538961038961039
32 0.538961038961039
33 0.5454545454545454
34 0.512987012987013
35 0.525974025974026
36 0.5454545454545454
37 0.5194805194805194
38 0.538961038961039
39 0.538961038961039
40 0.551948051948052
41 0.512987012987013
42 0.5714285714285714
43 0.5064935064935064
44 0.5454545454545454
45 0.5324675324675324
46 0.5584415584415584
47 0.5454545454545454
48 0.57142857

<h1> Saving the KNN Model </h1>

In [40]:
import pickle
pickle_out = open("KNN-ModelWeekly63.pickle", "wb")
pickle.dump(knn, pickle_out)
pickle_out.close()

In [2]:
X[1]

array([[0.        , 0.        , 0.        , 0.        , 0.39922515,
        0.41153838, 0.40758761, 0.40745592, 0.36630208, 0.45269222],
       [0.        , 0.        , 0.        , 0.        , 0.55678258,
        0.16054829, 0.00598181, 0.05977971, 0.15200467, 0.79843759]])